<?php 
$_COG_ITEM_CODE = 'ABOUT2';
$_COG_ITEM_NAME = " Message";
$_COG_ICON = "fa-info-circle";

//เซ็ตเมนูด้านซ้าย
$_COG_ALLOW_TEXT_FULL_PAGE = false;//text col-md-12
$_COG_ALLOW_LEFT_MENU = false;
$_COG_ALLOW_LEFT_MENU_ITEMS = true;
$_COG_ALLOW_LEFT_MENU_GALLERY = false;
$_COG_ALLOW_CATEGORY = false;
$_COG_ALLOW_CATEGORY_SUB = false;
$_COG_ALLOW_TAG = false;
$_COG_ALLOW_PROPERTIES = false;
$_COG_ALLOW_LEFT_MENU_TEAM = false;
$_COG_PROPERTIES_OPTION = false;
$_COG_ALLOW_MASTER_DETAIL = true;
$_COG_ALLOW_ROAD = false;
$_COG_ALLOW_LEFT_MENU_ITEMS_SUB = false;
$_COG_ALLOW_LEFT_FEEDBACK = false;

//เซ็ตหน้า itemCategoryDetail.php
$_COG_CATEGOTY_MAIN_IMAGE = false;
$_COG_CATEGOTY_MAIN_IMAGE2 = false;
$_COG_CATEGOTY_ICON = false;
$_COG_CATEGOTY_SHORT_DESCRIPTION = false;
$_COG_CATEGOTY_DETAIL = false;

//เซ็ตหน้า itemSubCategoryDetail.php
$_COG_CATEGOTY_SUB_MAIN_IMAGE = false;
$_COG_CATEGOTY_SUB_DETAIL = false;
$_COG_CATEGOTY_SUB_ICON = false;


//เซ็ตหน้า itemPropertiesDetail.php
$_COG_PROPERTIES_IMAGE = false;

//เซ็ตหน้า itemDetailGallery.php
$_COG_ALLOW_GALLERY_SIZE = "280x280";
$_COG_ALLOW_GALLERY_NAME = false;
$_COG_ALLOW_GALLERY_DETAIL = false;
$_COG_ALLOW_GALLERY_DETAIL2 = false;
$_COG_ALLOW_GALLERY_LINKWEB = false;

//เซ็ตหน้า itemFeedBack.php
$_COG_REVIEW_STAR = true;
$_COG_REVIEW_POSITION = true;

//เซ็ตหน้า MasterDetail.php
$_COG_ALLOW_MASTER_GALLERY_SIZE = "500x400";
$_COG_ALLOW_MASTER_GALLERY = false;
$_COG_ALLOW_MASTER_GALLERY2 = false;
$_COG_ALLOW_MASTER_GALLERY3 = false;
$_COG_ALLOW_MASTER_VIDEO = false;
$_COG_ALLOW_MASTER_VIDEO2 = false;// Video Local
$_COG_ALLOW_MASTER_TITLE = false;
$_COG_ALLOW_MASTER_HTML_EDITOR = true;
$_COG_ALLOW_MASTER_HTML_EDITOR2 = false;
$_COG_ALLOW_MASTER_HTML_EDITOR3 = false;
$_COG_ALLOW_MASTER_SHORT_DESCRIPTION = false;
$_COG_ALLOW_MASTER_FILE_DOWNLOAD = false;
$_COG_ALLOW_MASTER_MAPLOCATION = false;
$_COG_ALLOW_MASTER_LINK = false;
$_COG_ALLOW_MASTER_ACTIVE = false;
$_COG_ALLOW_MASTER_YEAR = false;
$_COG_ALLOW_MASTER_AUTHOR = false;
$_COG_ALLOW_MASTER_PHONE = false;
$_COG_ALLOW_MASTER_MOBILE = false;
$_COG_ALLOW_MASTER_FAX = false;
$_COG_ALLOW_MASTER_EMAIL = false;
$_COG_ALLOW_MASTER_SOCIAL_MEDIA = false;
$_COG_ALLOW_MASTER_TAG = false;
$_COG_ALLOW_MASTER_AMOUNT = false;
$_COG_ALLOW_MASTER_AMOUNT_DECIMAL = 0;
//PROPERTIES
$_COG_ALLOW_MASTER_PROPERTIES = false;
$_COG_ALLOW_MASTER_PROPERTIES_TITLE = "เวลาทำการ";


//เซ็ตหน้า item.php,itemDetail.php
$_COG_ALLOW_TITLE = true;
$_COG_ALLOW_REF_CODE = false;
$_COG_ALLOW_SHORT_DESCRIPTION = false;
$_COG_ALLOW_AUTHOR = false;
$_COG_ALLOW_REF_CISTOMER = false;
$_COG_ALLOW_DATE = false;
$_COG_ALLOW_SEO = false;
$_COG_ALLOW_GALLERY = false;
$_COG_ALLOW_GALLERY2 = false;
$_COG_ALLOW_MAIN_IMAGE_SIZE = "1200x900";
$_COG_ALLOW_MAIN_IMAGE = false;
$_COG_ALLOW_HTML_LOGO = false;
$_COG_ALLOW_MAIN_IMAGE3 = false;
$_COG_ALLOW_HTML_ICON = false;
$_COG_ALLOW_MAIN_VIDEO = false;
$_COG_ALLOW_MAIN_VIDEO2 = false;// Video Local
$_COG_ALLOW_HTML_EDITOR = true;
$_COG_ALLOW_HTML_EDITOR2 = false;
$_COG_ALLOW_HTML_EDITOR3 = false;
$_COG_ALLOW_HTML_EDITOR4 = false;
$_COG_ALLOW_HTML_LINK = false;
$_COG_ALLOW_HTML_DETAIL = false;//ตำแหน่ง
$_COG_ALLOW_HTML_PHONE = false;
$_COG_ALLOW_HTML_MOBILE = false;
$_COG_ALLOW_HTML_FAX = false;
$_COG_ALLOW_HTML_EMAIL = false;
$_COG_ALLOW_HTML_ADDRESS = false;
$_COG_ALLOW_HTML_MAPLOCATION = false;
$_COG_ALLOW_FIRST_SHORT_DESCRIPTION = false;
$_COG_ALLOW_SOCIAL_MEDIA = false;
$_COG_ALLOW_SOCIAL_FILE_DOWNLOAD = false;
$_COG_ALLOW_SOCIAL_FILE_DOWNLOAD2 = false;
$_COG_ALLOW_RANKING = false;
$_COG_ALLOW_NEW = false;
$_COG_ALLOW_FEEDBACK = false;
$_COG_ALLOW_SUBITEM = false;
$_COG_ALLOW_PROJECT = false;
$_COG_ALLOW_YEAR = false;
$_COG_ALLOW_HOUR = false;
$_COG_ALLOW_AMOUNT = false;
$_COG_ALLOW_FIRST_AMOUNT = false;
$_COG_ALLOW_AMOUNT_DECIMAL = 0;
$_COG_ALLOW_STATUS = false;
$_COG_ALLOW_PROVINCE = false;

//ITEMS
$_COG_REF_SELECT_ITEM = false;
$_COG_REF_SELECT_ITEM_TITLE = "TITLE_PORT_NAME...";
$_COG_REF_SELECT_ITEM_CODE = "PORT_CODE...";
$_COG_REF_SELECT_ITEM_IMAGE = false;
$_COG_REF_SELECT_ITEM_ICON = false;
//ITEMS 2
$_COG_REF_SELECT_ITEM2 = false;
$_COG_REF_SELECT_ITEM_TITLE2 = "TITLE_PORT_NAME...";
$_COG_REF_SELECT_ITEM_CODE2 = "PORT_CODE...";
$_COG_REF_SELECT_ITEM_IMAGE2 = false;
$_COG_REF_SELECT_ITEM_ICON2 = false;

//PROPERTIES
$_COG_ITEM_PROPERTIES = false;
$_COG_ITEM_PROPERTIES_TITLE = "เวลาทำการ";

?>
